### ISSUE TITLE
Filtering by name doesn't work

### ISSUE THREAD

**Issue by joekaiser** [Kazumasan/ulauncher-sessions#1]
Filtering by name doesn't work after you enter two characters. Note: `e` is the trigger keyword i have set

**Step1:** Enter your keyword. All sessions show as expected.
![image](https://user-images.githubusercontent.com/1521110/110988529-84349800-8325-11eb-9223-5f6103742e78.png)

**Step2:** Enter one character. You can see highlighting begins to work
![image](https://user-images.githubusercontent.com/1521110/110988649-aa5a3800-8325-11eb-9554-ffdecac84e5e.png)

**Step3:** Enter another character. Filtering breaks.
![image](https://user-images.githubusercontent.com/1521110/110988719-c65dd980-8325-11eb-81f4-343d096488f3.png)

**Expected:** The list should be filtered to include `Api` and `App`

_Ulauncher version 5.10.0_
_Extension version latest_

**Comment by Kazumasan** [comment]
Thanks for spotting, strangly i don't have that problem on my main machine but on my laptop. Will investigate.

Edit: query will be filtered by file path not name i already spottet that but somehow forgot to fix it...
will do so in the next couple of days.

**Comment by Kazumasan** [comment]
@joekaiser i pushed a fix. Hope it's all set now.

**Comment by joekaiser** [comment]
:green_heart:  works great.
